vehicle_chassis_driver:
  ros__parameters:
    serial_baud_rate: 115200
    usart_port_name: /dev/wheeltec_controller
    odom_frame_id: odom_combined
    robot_frame_id: base_footprint
    gyro_frame_id: gyro_link
    odom_x_scale: 1.0
    odom_y_scale: 1.0
    odom_z_scale_positive: 1.0
    odom_z_scale_negative: 1.0